### ISSUE TITLE
Bearer_token help!

### ISSUE THREAD

**Issue by Cheezizy** [BeauAgst/HQT#2]
How do you get the bearer token retrieved from the HQ Trivia API? Do you need to get this before every game or is it the same for each game? Add me on discord if you want to chat there Cheesy #8556. Thanks

**Comment by metacurb** [comment]
Hi @Cheezizy, I recommend you take a look at [Charles proxy.](https://www.charlesproxy.com/)

This will allow you to proxy traffic coming from your device, and you'll be able to find the bearer that is sent within each request. There should be plenty of tutorials online. Thanks!
