### ISSUE TITLE
2 Issues - Need help.

### ISSUE THREAD

**Issue by lkjhgfdsas** [BeauAgst/HQT#3]
**Currently I am having two issues:**

> 1. I am trying to do `touch .env` in terminal but no file is created (I am in the HQT file)

> 2. When entering the `Bearer Token` do we include "Bearer" or just enter the letters and numbers, all one line?

Using macOS High Sierra. 

Any help much appreciated. Thank you for creating this project

**Comment by metacurb** [comment]
Hey @lkjhgfdsas ,

if `touch .env` isn't creating the file, you can manually create a file called `.env` yourself. 

When storing your bearer token in the `.env` file, just enter the long string, there is no need to include `Bearer`. 

If you fancy adding/updating instructions for macOS, please create a pull request.

Thanks!

**Comment by lkjhgfdsas** [comment]
> UPDATE: Works fine

Thanks for the help. I created my own `.env` file and imputed the information needed, weirdly though it does not show up in the folder. I'll see if it works.
